# Generated by Django 3.1.5 on 2021-01-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cur_country',
            new_name='cur_city',
        ),
    ]
