# Generated by Django 3.1.5 on 2021-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210117_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.URLField(default='https://picsum.photos/200', max_length=100),
        ),
    ]
